# Generated by Django 2.2.2 on 2019-06-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='end_time',
            field=models.TimeField(),
        ),
    ]
