# Generated by Django 2.2.2 on 2019-06-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190619_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='day',
            field=models.DateField(),
        ),
    ]
