# Generated by Django 2.2.2 on 2019-07-03 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20190702_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_extension', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pagevisited',
            name='activity',
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ActivityType'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='productive',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='activities',
            unique_together={('user', 'day', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='activitytype',
            unique_together={('user', 'type_name')},
        ),
        migrations.AlterUniqueTogether(
            name='sitetype',
            unique_together={('user', 'type_name')},
        ),
        migrations.DeleteModel(
            name='CombinedActivites',
        ),
        migrations.DeleteModel(
            name='PageVisited',
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Activities'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Site'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extension',
            name='site_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SiteVisit'),
        ),
        migrations.AddField(
            model_name='extension',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='activities',
            name='site',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='universal',
        ),
        migrations.AlterUniqueTogether(
            name='sitevisit',
            unique_together={('user', 'day', 'start_time', 'end_time', 'site')},
        ),
    ]
