# Generated by Django 2.2.2 on 2019-07-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190703_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='universal',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
