# Generated by Django 2.2.2 on 2019-07-06 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_activitytype_universal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisit',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='site_visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SiteVisit'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ActivityType'),
        ),
    ]
