# Generated by Django 2.2.2 on 2019-07-06 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190706_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='site_visit',
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Activity'),
        ),
    ]
