# Generated by Django 2.2.2 on 2019-07-16 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190716_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisit',
            name='activity',
        ),
        migrations.CreateModel(
            name='SiteVisitToActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Activity')),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SiteVisit')),
            ],
            options={
                'unique_together': {('activity', 'site_visit')},
            },
        ),
    ]
